config/routes.rb
BookReview::Application.routes.draw do
  
  resources :reviews

  resources :book_categories

  resources :categories

  resources :authors

  resources :authors
  resources :books
  get "reviews/book/:book_id" , to: "reviews#reviews_by_book", as: "reviews_of_book"
  
  get "book_categories/category/:category_id" , to: "book_categories#books_by_category"
  get "book_categories/book/:book_id" , to: "book_categories#categories_by_book", as: "categories_of_book"
  
  get "books/author/:author_id" , to: "books#books_by_author", as: "books_by_author"

  get "admins/index" , to: "admins#index", as: "admin_index"
  
  get "books/mob/index", to: "books#mob_index", as: "books_mob_index"

   root 'books#index'

  

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :books, :dependent => :destroy
    validates :first_name, presence: true
    validates :last_name, presence: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    #http_basic_authenticate_with name: "dhh", password: "secret", except: :index
    before_action :set_author, only: [:show, :edit, :update, :destroy]
    rescue_from ActiveRecord::RecordNotUnique, :with => :unique_record_handler
    
    def index
        @authors = Author.includes(:books)
    end

    def mob_index
        @authors = Author.includes(:books)
        render layout: "mob-application"
    end

    def show
        @author = Author.find(params[:id])
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)

        respond_to do |format|
          if @author.save
            format.html { redirect_to @author, notice: 'Author was successfully created.' }
            format.json { render action: 'show', status: :created, location: @author }
          else
            format.html { render action: 'new' }
            format.json { render json: @author.errors, status: :unprocessable_entity }
          end
        end
    end

    def update
        respond_to do |format|
          if @author.update(author_params)
            format.html { redirect_to @author, notice: 'Author was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @author.errors, status: :unprocessable_entity }
          end
        end
    end

    def destroy
        @author.destroy
        respond_to do |format|
          format.html { redirect_to authors_url }
          format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_author
          @author = Author.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def author_params
          params[:author].permit(:first_name, :last_name)
        end

        def unique_record_handler(exception)
            redirect_to new_author_url, :duplicate_record_exception => "Author already exists! can not add a duplicate."
        end  
end

app/helpers/authors_helper.rb
module AuthorsHelper

    def books_by_link(author_id, num_books)
        if (num_books > 0)
            link_to( "%d" % num_books, books_by_author_path(:author_id => author_id), :class => "wide_link" )
        else 
            "None"
        end
    end
    
    def display_is_admin
        if  session.id.nil?
            "<p>Admin</p>"
        else
            "<p>Anon</p>"
        end 
    end

end

app/views/authors/_form.html.erb
<%= form_for(@author, html: {class:"pure-form pure-form-stacked padded_form"}) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<% if flash[:duplicate_record_exception] %>
<div id="error_explanation">
    <%= flash[:duplicate_record_exception] %>
</div>
<% end %>
    <fieldset>
        <legend>Author Form</legend>

        <%= f.label :first_name %>
        <%= f.text_field :first_name %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      <%= f.submit :class => "pure-button pure-button-primary"  %>
    </fieldset>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table class="pure-table" style="letter-spacing:normal;">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Books</th>
      <th></th>
      <th></th>
      <th></th>
  </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
        <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td><%= books_by_link(author.id, author.books.count) %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>Add New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<p> Session: 
<%= session[:uid] %>

</p>

<div class="pure-g">
    <div class="pure-u-1-4">
        <%= @author.first_name %>
    </div>

    <div class="pure-u-1-4">
        <%= @author.last_name %>
    </div>
</div>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>