config/routes.rb
BookReview::Application.routes.draw do
  
  resources :reviews

  resources :book_categories

  resources :categories

  resources :authors

  resources :authors
  resources :books
  get "reviews/book/:book_id" , to: "reviews#reviews_by_book", as: "reviews_of_book"
  
  get "book_categories/category/:category_id" , to: "book_categories#books_by_category"
  get "book_categories/book/:book_id" , to: "book_categories#categories_by_book", as: "categories_of_book"
  
  get "books/author/:author_id" , to: "books#books_by_author", as: "books_by_author"

  get "admins/index" , to: "admins#index", as: "admin_index"
  
  get "books/mob/index", to: "books#mob_index", as: "books_mob_index"

   root 'books#index'

  

end

app/models/book_category.rb
class BookCategory < ActiveRecord::Base
  belongs_to :book
  belongs_to :category
  validates :book_id, presence: true, numericality: {only_integer: true}
  validates :category_id, presence: true, numericality: {only_integer: true}
end

app/controllers/book_categories_controller.rb
class BookCategoriesController < ApplicationController
    before_action :set_book_category, only: [:show, :edit, :update, :destroy]
    respond_to :js, :html
    rescue_from ActiveRecord::RecordNotUnique, :with => :unique_record_handler


    # GET /book_categories
    # GET /book_categories.json
    def index
        @book_categories = BookCategory.all.includes( :book,  :category)
    end

    # GET /book_categories/1
    # GET /book_categories/1.json
    def show
        @book_categories = BookCategory.find(params[:id], :include => :book, :include => :category)
    end

    # GET /book_categories/new
    def new
        @book_category = BookCategory.new
    end

    # GET /book_categories/1/edit
    def edit
    end

    # POST /book_categories
    # POST /book_categories.json
    def create
        @book_category = BookCategory.new(book_category_params)


        respond_to do |format|
          if @book_category.save
            format.html { redirect_to @book_category, notice: 'Book category was successfully created.' }
            format.json { render action: 'show', status: :created, location: @book_category }
          else
            format.html { render action: 'new' }
            format.json { render json: @book_category.errors, status: :unprocessable_entity }
          end
        end
    end

    # PATCH/PUT /book_categories/1
    # PATCH/PUT /book_categories/1.json
    def update
    respond_to do |format|
      if @book_category.update(book_category_params)
        format.html { redirect_to @book_category, notice: 'Book category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book_category.errors, status: :unprocessable_entity }
      end
    end
    end

    # DELETE /book_categories/1
    # DELETE /book_categories/1.json
    def destroy
    @book_category.destroy
    respond_to do |format|
      format.html { redirect_to book_categories_url }
      format.json { head :no_content }
    end
    end

    def  books_by_category
        @book_categories =  BookCategory.includes(:book).select("book.title, book.author.last_name, book.author.first_name, book.reviews.count").where("book_categories.category_id = ? ", params[:category_id])
        @category = Category.select("title").where("categories.id = ?", params[:category_id]).distinct.first
        @category_title = @category.title
        {:book_categories => @book_categories, :category_title => @category_title}
    end

    def categories_by_book
        @book_categories =  BookCategory.includes(:category).select("category.title").where("book_categories.book_id = ? ", params[:book_id])
        @book = Book.includes(:author).where("id = ?", params[:book_id]).distinct.first
        {:book_categories => @book_categories, :book => @book}
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_category
      @book_category = BookCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_category_params
      params[:book_category].permit(:book_id, :category_id)
    end
    
    def unique_record_handler(exception)
        redirect_to new_book_category_url, :duplicate_record_exception => "Book Category already exists! can not add a duplicate."
    end  


end

app/helpers/book_categories_helper.rb
module BookCategoriesHelper
end

app/views/book_categories/_form.html.erb
<%= form_for(@book_category, html: {class:"pure-form pure-form-stacked padded_form"}) do |f| %>
  <% if @book_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_category.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  </ul>
   </div>
  <% end %>
  <% if flash[:duplicate_record_exception] %>
    <div id="error_explanation">
        <%= flash[:duplicate_record_exception] %>
    </div>

  <% end %>
    <fieldset>
        <legend>Book Category Form</legend>

        <%= select("book_category", "book_id", Book.all.collect {|p| [ p.title  , p.id ] }, {include_blank: 'None'}) %>
        <%= select("book_category", "category_id", Category.all.collect {|p| [ p.title  , p.id ] }, {include_blank: 'None'}) %>

      <%= f.submit :class => "pure-button pure-button-primary actions"  %>
    </fieldset>
<% end %>

app/views/book_categories/books_by_category.html.erb
<h1><%= @category_title %> Books</h1>

<table class="pure-table" style="letter-spacing:normal;">
  <thead>
      <tr>

      <th>Book</th>
      <th>Author</th>
      <th>Reviews</th>
    </tr>
  </thead>

  <tbody>
    <% @book_categories.each do |book_category| %>
        <tr>
        <td><%= book_category.book.title %></td>
        <td>
        
            <%= book_category.book.author.last_name %> , 
            <%= book_category.book.author.first_name %>
        </td>
        <% if book_category.book.reviews.count > 0 %>
            <td>
                <a style="display:block;width:100%;text-align:right;" href="/reviews/book/<%= book_category.book.id %>">
                    <%= book_category.book.reviews.count %>
                </a>
            </td>
        <% else %>
            <td> No Reviews Yet.</td>
            <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book category', new_book_category_path %>

app/views/book_categories/categories_by_book.html.erb
<h1><%= link_to(@book.title, book_path(:id => @book.id)) %></h1>

<div>Written by:&nbsp;
    <span style="font-size:larger;">
        <%= link_to( @book.author.last_name + ", " +  @book.author.first_name, author_path(:id => @book.author.id)) %> 
    </span>
</div>
<br/>

<table class="pure-table" style="letter-spacing:normal;">
  <thead>
      <tr>
      <th>Categories</th>
    </tr>
  </thead>

  <tbody>
    <% @book_categories.each do |book_category| %>
        <tr>
        <td><%= book_category.category.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/book_categories/edit.html.erb
<h1>Editing book_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_category %> |
<%= link_to 'Back', book_categories_path %>

app/views/book_categories/index.html.erb
<h1>Book Categories</h1>

<table class="pure-table" style="letter-spacing:normal;">
  <thead>
      <tr>

      <th>Book</th>
      <th>Category</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @book_categories.each do |book_category| %>
        <tr>
        <td><%= book_category.book.title %></td>
        <td><%= book_category.category.title %></td>
        <td>
        
            <%= book_category.book.author.last_name %> , 
            <%= book_category.book.author.first_name %>
        </td>
        <td><%= link_to 'Show', book_category %></td>
        <td><%= link_to 'Edit', edit_book_category_path(book_category) %></td>
        <td><%= link_to 'Destroy', book_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book category', new_book_category_path %>

app/views/book_categories/new.html.erb
<h1>Add New Book Category</h1>

<%= render 'form' %>

<%= link_to 'Back', book_categories_path %>

app/views/book_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_book_category_path(@book_category) %> |
<%= link_to 'Back', book_categories_path %>