config/routes.rb
BookReview::Application.routes.draw do
  
  resources :reviews

  resources :book_categories

  resources :categories

  resources :authors

  resources :authors
  resources :books
  get "reviews/book/:book_id" , to: "reviews#reviews_by_book", as: "reviews_of_book"
  
  get "book_categories/category/:category_id" , to: "book_categories#books_by_category"
  get "book_categories/book/:book_id" , to: "book_categories#categories_by_book", as: "categories_of_book"
  
  get "books/author/:author_id" , to: "books#books_by_author", as: "books_by_author"

  get "admins/index" , to: "admins#index", as: "admin_index"
  
  get "books/mob/index", to: "books#mob_index", as: "books_mob_index"

   root 'books#index'

  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all.includes( :book)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @reviews = Review.find(params[:id], :include => :book)
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  def reviews_by_book
      @reviews =  Review.where("reviews.book_id = ? ", params[:book_id])

      #@reviews =  Review.find(:include => :book).where("reviews.book_id = ?", params[:book_id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params[:review].permit(:body, :stars, :book_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review, html: {class:"pure-form pure-form-stacked", style: "padding:10px;margin:6px;"}) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <fieldset>
        <legend>Review a Book Form</legend>

        <%= f.label :body %>
        <%= f.text_area :body %>

        <%= f.label :stars %>
        <%= f.text_field :stars %>
        
        <%= select("review", "book_id", Book.all.collect {|p| [ p.title , p.id ] }, {include_blank: 'None'}) %>

      <%= f.submit :class => "pure-button pure-button-primary actions"  %>
    </fieldset>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table class="pure-table" style="letter-spacing:normal;">

  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Stars</th>
      <th>Details</th>
      <th></th>
      <th></th>
  </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
        <tr>
            <td><%= review.book.title %></td>
            <td><%= review.book.author.last_name %>, <%= review.book.author.first_name%></td>
            <td>Stars <%= review.stars %>  </td>
            <td><%= link_to 'Read Detailed Review', review %></td>
            <td><%= link_to 'Edit', edit_review_path(review) %></td>
            <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/reviews_by_book.html.erb
<h1>Reviews by Book</h1>

<table class="pure-table" style="letter-spacing:normal;">

  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Stars</th>
      <th>Details</th>
      <th></th>
      <th></th>
  </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
        <tr>
            <td><%= review.book.title %></td>
            <td><%= review.book.author.last_name %>, <%= review.book.author.first_name%></td>
            <td>Stars <%= review.stars %>  </td>
            <td><%= link_to 'Read Detailed Review', review %></td>
            <td><%= link_to 'Edit', edit_review_path(review) %></td>
            <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>


<div class="pure-g-r" style="letter-spacing:normal;">
    <div class="pure-u-3-5">
        <span style="font-weight:bold;"><%= @review.book.title %></span>
    </div>
</div>

<div class="pure-g-r" style="letter-spacing:normal;">
    <div class="pure-u-2-5">
        <span style="font-weight:bold;"><%= @review.book.author.last_name %>, <%= @review.book.author.first_name%></span>
    </div>
    <div class="pure-u-1-5">Stars <%= @review.stars %></div>
</div>

<div class="pure-g-r" style="letter-spacing:normal;">
    <%= @review.body %>

</div>
<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>